##### task1

In [2]:
import pandas as pd
df_titanic = pd.read_excel("../data/titanic.xlsx")
def check_survived(x):
    return x[x["Survived"]==1].copy() 
df_titanic.pipe(check_survived)
def fill_AgeNaNs(x):
    x.loc[:, "Age"] = x["Age"].fillna(x["Age"].mean())
    return x
df_titanic.pipe(fill_AgeNaNs)
def Fare_per_age(x):
    x.loc[:, "Fare_per_Age"]=x['Fare']/x['Age']
    return x
df_titanic = (
    df_titanic.pipe(check_survived)
    .pipe(fill_AgeNaNs)
    .pipe(Fare_per_age)
)
df_titanic

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Fare_per_Age
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,1.875876
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0.304808
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,1.517143
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S,0.412344
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C,2.147914
...,...,...,...,...,...,...,...,...,...,...,...,...,...
875,876,1,3,"Najib, Miss. Adele Kiamie ""Jane""",female,15.0,0,0,2667,7.2250,NaN,C,0.481667
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C,1.484970
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,NaN,S,1.040000
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,1.578947
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,1.153846

##### task2

In [ ]:
df_flights = pd.read_parquet("../data/flights")
def filter_by_delay(df):
    return df[pd.to_numeric(df["DepDelay"], errors="coerce")>30].copy()

def Delay_per_Hour(df):
    df.loc[:, "Delay_Per_Hour"]= pd.to_numeric(df["DepDelay"], errors="coerce")/pd.to_numeric(df["Duration"], errors="coerce")

df_flights=(
    df_flights.pipe(filter_by_delay)
    .pipe(Delay_per_Hour)
)
df_flights

KeyError: 'duration'